### PR TITLE
Input zacros

### PR DESCRIPTION
**Pull request by nfaguirrec**

### CODE REVIEW

**Comment by lopeztarifa** [comment]
@nfaguirrec great work!

I have only one question. This is what we output:

```
step H2*-f,*-f:(1,2)-->*-f,*-f:H2:(1,2)
  gas_species H2 1
  sites 2
  neighboring 1-2
  initial
    1 H2* 1
    2 * 1
  final
    1 * 1
    2 * 1
  site_types f f
  pre_expon 1.000000e+13
  pe_ratio 0.676
  activ_eng 0.2
end_step
```

But, according to the Manual, it should be something like:

```
step H2*-f,*-f:(1,2)-->*-f,*-f:H2:(1,2)
  gas_reacs_prods H2 -1
  sites 2
  neighboring 1-2
  initial
    1 H2* 1
    2 * 1
  final
    1 * 1
    2 * 1
  site_types f f
  pre_expon 1.000000e+13
  pe_ratio 0.676
  activ_eng 0.2
end_step
```
Page 38 of the Zacros manual: 

> [_gas_reacs_prods str1 int1 ..._]: Provides information about the gas species participating in the mechanism. The name of the first gas species is given in str1 whereas the stoichiometry is given by integer int1 (negative for reactants and positive for products).

**Comment by nfaguirrec** [comment]
So, it is correct! In this case, the H2 is a product, so its stoichiometry is positive. The two adsorbed H atoms on the surface H*-f,H*-f  join to form H2 in the gas phase. On the other side, you are right. We need to include the calculation of the stoichiometry value. For now, it is just +1, or -1, but here is where the mass balance of the clusters plays a role and will help us to fix this. Let's include this a bit later on.

**Comment by nfaguirrec** [comment]
Done! Nice catch! Thanks!

**Comment by lopeztarifa** [comment]
Closes #6 and #18

**Comment by nfaguirrec** [comment]
By the way. The stoichiometry is already included in this version :) For example, if the Cluster has n times H2 gas-species, it prints out "H2 +/-n" being n the number of these molecules in the cluster.

**Pull request merged**
